version: '3'

services:
  chensino-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: chensino-mysql
    image: chensino-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./chensino-mysql:/var/lib/mysql
    command: --lower_case_table_names=1
    networks:
      - custom

  chensino-redis:
    container_name: chensino-redis
    image: redis:6.2.6
    restart: no
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis/conf:/etc/redis  #指定外部配置
      - ./redis/data:/data #指定数据目录，此配置一定要有
    ports:
      - "6379:6379"
    networks:
      - custom

  chensino-rabbitmq:
    restart: no
    container_name: chensino-rabbitmq
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/conf:/etc/rabbitmq
      - ./rabbitmq/data:/var/lib/rabbitmq
#      - ./rabbitmq/log:/var/log/rabbitmq
    ports:
      - "15672:15672" #web页面
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: chensino
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - custom

  chensino-minio:
    restart: no
    container_name: chensino-minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001" #web页面
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio/
    environment:
      - "MINIO_ACCESS_KEY=admin"
      - "MINIO_SECRET_KEY=12345678"
    command: server --console-address ':9001' /data
    privileged: true
    networks:
      - custom

  chensino-elasticsearch:
    restart: no
    container_name: chensino-elasticsearch
    image: elasticsearch:8.11.3
    hostname: chensino-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits: # 栈内存的上限
      memlock:
        soft: -1    # 不限制
        hard: -1    # 不限制
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    networks:
      - custom

  chensino-kibana:
    restart: no
    container_name: chensino-kibana
    image: kibana:8.11.3
    environment:
      - ELASTICSEARCH_HOSTS=http://chensino-elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    networks:
      - custom
    depends_on:
      - chensino-elasticsearch


#  core-biz:
#    build:
#      context: ./core/core-biz
#    depends_on:
#      - chensino-redis
#      - chensino-mysql
#      - chensino-rabbitmq
#    restart: no
#    container_name: core-biz
#    image: chensino-core-biz
#    ports:
#      - "8888:8888"
#    networks:
#      - custom

networks:
  custom:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.0.0/16
          gateway: 172.55.0.1