server:
  port: 8888
  tomcat:
    threads:
      max: 3
    max-connections: 2
    connection-timeout: 1000
    accept-count: 10
    ##优雅关机，打开 优雅关机后要配合kill -2 <processId>，不能kill -9
  shutdown: graceful
#  servlet:
#    context-path: /chensino
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: a5141e3a81e66f967483
            client-secret: f7bfbb863567e6433c9c32f0a877751675ed9bba
            client-name: SonoScape-Auth
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,message.read,message.write
            redirect-uri: http://digital-gateway:8005/auth/oauth/callback
            provider: SonoScape
        provider:
          Sonoscape:
            authorizationUri: https://github.com/login/oauth/authorize
            tokenUri: https://github.com/login/oauth/access_token
            userInfoUri: https://api.github.com/user
            userNameAttribute: id

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      location: /tmp  #上传临时存放，生产环境最好自定义
  freemarker:
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates/
  main:
    #懒加载bean,用到的时候再创建，默认为false,类似BeanFactory
    lazy-initialization: true
  application:
    name: chensino-core
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:p6spy:mysql://${MYSQL_HOST:chensino-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:chensino}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  data:
    redis:
      database: 0
      password: 123456
      host: chensino-redis
      timeout: 1000
      port: 6379
      jedis:
        pool:
          enabled: true
          max-active: 8 #池中最大连接数
          max-idle: 8 #最大空闲连接数
          max-wait: 1000
          min-idle: 0
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
token:
  expiration: 36000

## 暴露actuator所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
        ##自定义监控路径，默认为/actuator
      base-path: /management
info:
  app:
    java:
      source: 17
      target: 17
#security:
#  oauth2:
#    client:
#      client-id: pig
#      client-secret: pig
#      user-authorization-uri: http://127.0.0.1:3000/oauth/authorize
#      access-token-uri: http://127.0.0.1:3000/oauth/token
#      scope: server
#    resource:
#      loadBalanced: true
#      token-info-uri: http://127.0.0.1:3000/oauth/check_token
minio:
  endpoint: chensino-minio:9000
  region: ap-southeast-1
  access-key: Nnz2FawqpPnJLdeg
  secret-key: 0nUgm71w7Tzo7RpqgXVuVkJpDu2IIMMH

oauth:
  github:
    clientId: 18730ff09031fd6fcc754
    secret: 1db14a3ea61e4502e09959d71489dc0d2fa10d47e
    redirectUri: http://chensino:8888/login/oauth2/code/github
    authorizeUrl: https://github.com/login/oauth/authorize
    accessTokenUrl: https://github.com/login/oauth/access_token
    userInfoUrl: https://api.github.com/user
    frontendHost: http://chensino-web:3333

springfox:
  documentation:
    swagger-ui:
      enabled: true


security:
  whiteList:
    - /login/**
    - /management/**
    - /management
    - /swagger-ui/**
    - /swagger-resources/**
    - /webjars/**
    - /v3/api-docs
    - /v3/api-docs/**
    - /error
    - /favicon.ico
