server:
  port: 8888
  tomcat:
    threads:
      max: 3
    max-connections: 2
    connection-timeout: 1000
    accept-count: 10
    ##优雅关机，打开 优雅关机后要配合kill -2 <processId>，不能kill -9
  shutdown: graceful
#  servlet:
#    context-path: /chensino
spring:
  main:
    #懒加载bean,用到的时候再创建，默认为false,类似BeanFactory
    lazy-initialization: true
  application:
    name: chensino-core
  redis:
    database: 0
    password: sonoscape
    host: chensino-redis
    port: 6379
    timeout: 1000
    jedis:
      pool:
        enabled: true
        max-active: 8 #池中最大连接数
        max-idle: 8 #最大空闲连接数
        max-wait: 1000
        min-idle: 0
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:p6spy:mysql://${MYSQL_HOST:chensino-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:chensino}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
token:
  expiration: 36000

## 暴露actuator所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
        ##自定义监控路径，默认为/actuator
      base-path: /management
info:
  app:
    java:
      source: 11
      target: 11
#security:
#  oauth2:
#    client:
#      client-id: pig
#      client-secret: pig
#      user-authorization-uri: http://127.0.0.1:3000/oauth/authorize
#      access-token-uri: http://127.0.0.1:3000/oauth/token
#      scope: server
#    resource:
#      loadBalanced: true
#      token-info-uri: http://127.0.0.1:3000/oauth/check_token
minio:
  endpoint: chensino-minio:9000
  region: ap-southeast-1
  port: 9000
  access-key: HqufY5uPWRYVj49l
  secret-key: JTUw9VxTkceN0VpYqIQJ1UAGSRkrYtA8
  secure: false
  bucket-name: chensino
#minio:
#  endpoint: http://obs.ap-southeast-1.myhuaweicloud.com
#  access-key: 2KBFFO4DOONQYSKLRYEP
#  secret-key: rhwiVviDVbjfmUvFTHCAGmOj64PsL1hDIsrkje99
#  bucket-name: ccs
#  region: ap-southeast-1