package com.chensino.core.api.entity;

import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

/**
 *
 * Database Table Remarks:
 *   文件
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sys_file
 */
@TableName("t_sys_file")
public class SysFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.id
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.file_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   桶名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.bucket_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private String bucketName;

    /**
     * Database Column Remarks:
     *   文件原名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.original_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private String originalName;

    /**
     * Database Column Remarks:
     *   后缀
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.file_suffix
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private String fileSuffix;

    /**
     * Database Column Remarks:
     *   文件大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.file_size
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private Integer fileSize;

    /**
     * Database Column Remarks:
     *   业务类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.business_type
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private Integer businessType;

    /**
     * Database Column Remarks:
     *   对应业务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.business_id
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private Long businessId;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.create_user
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.create_time
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.update_user
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.update_time
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_file.del_flag
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    private Byte delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.id
     *
     * @return the value of t_sys_file.id
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.id
     *
     * @param id the value for t_sys_file.id
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.file_name
     *
     * @return the value of t_sys_file.file_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.file_name
     *
     * @param fileName the value for t_sys_file.file_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.bucket_name
     *
     * @return the value of t_sys_file.bucket_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.bucket_name
     *
     * @param bucketName the value for t_sys_file.bucket_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName == null ? null : bucketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.original_name
     *
     * @return the value of t_sys_file.original_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public String getOriginalName() {
        return originalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.original_name
     *
     * @param originalName the value for t_sys_file.original_name
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setOriginalName(String originalName) {
        this.originalName = originalName == null ? null : originalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.file_suffix
     *
     * @return the value of t_sys_file.file_suffix
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.file_suffix
     *
     * @param fileSuffix the value for t_sys_file.file_suffix
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.file_size
     *
     * @return the value of t_sys_file.file_size
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.file_size
     *
     * @param fileSize the value for t_sys_file.file_size
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.business_type
     *
     * @return the value of t_sys_file.business_type
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.business_type
     *
     * @param businessType the value for t_sys_file.business_type
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.business_id
     *
     * @return the value of t_sys_file.business_id
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.business_id
     *
     * @param businessId the value for t_sys_file.business_id
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.create_user
     *
     * @return the value of t_sys_file.create_user
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.create_user
     *
     * @param createUser the value for t_sys_file.create_user
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.create_time
     *
     * @return the value of t_sys_file.create_time
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.create_time
     *
     * @param createTime the value for t_sys_file.create_time
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.update_user
     *
     * @return the value of t_sys_file.update_user
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.update_user
     *
     * @param updateUser the value for t_sys_file.update_user
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.update_time
     *
     * @return the value of t_sys_file.update_time
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.update_time
     *
     * @param updateTime the value for t_sys_file.update_time
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.del_flag
     *
     * @return the value of t_sys_file.del_flag
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.del_flag
     *
     * @param delFlag the value for t_sys_file.del_flag
     *
     * @mbg.generated Fri Jun 02 15:41:39 CST 2023
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }
}