package com.chensino.common.log.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   记录数据操作历史
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_history_log
 */
@Data
public class HistoryLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.operate_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private Integer operateType;

    /**
     * Database Column Remarks:
     *   业务类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.business_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String businessType;

    /**
     * Database Column Remarks:
     *   关联业务的主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.business_id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private Long businessId;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.create_by
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String createBy;

    /**
     *
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.create_time
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.origin_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String originObj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.new_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String newObj;

}