package com.chensino.common.log.entity;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   记录数据操作历史
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_history_log
 */
public class HistoryLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.operate_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private Integer operateType;

    /**
     * Database Column Remarks:
     *   业务类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.business_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String businessType;

    /**
     * Database Column Remarks:
     *   关联业务的主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.business_id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private Long businessId;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.create_by
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.create_time
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.origin_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String originObj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_log.new_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    private String newObj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.id
     *
     * @return the value of t_history_log.id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.id
     *
     * @param id the value for t_history_log.id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.operate_type
     *
     * @return the value of t_history_log.operate_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.operate_type
     *
     * @param operateType the value for t_history_log.operate_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.business_type
     *
     * @return the value of t_history_log.business_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.business_type
     *
     * @param businessType the value for t_history_log.business_type
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.business_id
     *
     * @return the value of t_history_log.business_id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.business_id
     *
     * @param businessId the value for t_history_log.business_id
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.create_by
     *
     * @return the value of t_history_log.create_by
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.create_by
     *
     * @param createBy the value for t_history_log.create_by
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.create_time
     *
     * @return the value of t_history_log.create_time
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.create_time
     *
     * @param createTime the value for t_history_log.create_time
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.origin_obj
     *
     * @return the value of t_history_log.origin_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public String getOriginObj() {
        return originObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.origin_obj
     *
     * @param originObj the value for t_history_log.origin_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setOriginObj(String originObj) {
        this.originObj = originObj == null ? null : originObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_log.new_obj
     *
     * @return the value of t_history_log.new_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public String getNewObj() {
        return newObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_log.new_obj
     *
     * @param newObj the value for t_history_log.new_obj
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    public void setNewObj(String newObj) {
        this.newObj = newObj == null ? null : newObj.trim();
    }
}