package com.chensino.common.log.mapper;

import com.chensino.common.log.entity.HistoryLog;

public interface HistoryLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_log
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_log
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    int insert(HistoryLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_log
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    int insertSelective(HistoryLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_log
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    HistoryLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_log
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    int updateByPrimaryKeySelective(HistoryLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_log
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(HistoryLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_log
     *
     * @mbg.generated Tue Jun 13 11:23:55 CST 2023
     */
    int updateByPrimaryKey(HistoryLog row);
}